// import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Info from '../components/Info';
import NetworkSwitcher from '../components/Switcher';
import QueryErc20 from '@/components/QueryErc20'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Info />
        <NetworkSwitcher />
        <QueryErc20/>
        <div>修建分支</div>
      </main>
      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </>

  );
};

export default Home;